import { defineConfig } from "vite-plus";

export default defineConfig({
  test: {
    include: ["test/**/*.test.ts", "test/**/*.test.tsx"],
    exclude: ["node_modules/**", "dist/**", "e2e/**", "test/**/*.bun.test.ts"],
    // A couple of integration tests depend on live Redis/Mongo pub-sub & timer
    // timing; retry absorbs rare scheduling flakes (esp. under coverage load).
    retry: 2,
    coverage: {
      provider: "v8",
      include: ["src/**/*.ts"],
      exclude: [
        "src/ui/**",
        "src/entry-*.ts",
        "src/storage/sqlite.ts",
        "src/storage/libsql.ts",
        // CLI entry point: server I/O orchestration (the `serve` command starts a
        // long-lived server and never returns) — exercised by integration tests,
        // not unit coverage.
        "src/cli.ts",
      ],
      reporter: ["text", "html", "lcov"],
      thresholds: { statements: 92, branches: 85, functions: 90, lines: 92 },
    },
  },
  lint: {
    ignorePatterns: ["dist/**", "src/ui/**", "apps/**", "examples/**"],
  },
  // CHANGELOG.md is generated by changelogen (its own format) and rewritten on
  // every release — don't enforce our formatter on it.
  fmt: {
    ignorePatterns: ["CHANGELOG.md"],
  },
  staged: {
    // Pre-commit only formats (fast, and never errors on lint-ignored paths like
    // examples/**). Linting + typecheck run in the pre-push hook (`bun run check`)
    // and in CI, where ignorePatterns resolve against the whole repo.
    "*.{ts,tsx,md,mdx,json,jsonc,yml,yaml,css,html}": ["vp fmt"],
  },
  pack: {
    entry: [
      "src/index.ts",
      "src/core.ts",
      "src/schema.ts",
      "src/signing.ts",
      "src/receiver.ts",
      "src/testing.ts",
      "src/entry-storage-memory.ts",
      "src/entry-storage-file.ts",
      "src/entry-storage-redis.ts",
      "src/entry-storage-postgres.ts",
      "src/entry-storage-drizzle.ts",
      "src/entry-storage-mongodb.ts",
      "src/entry-storage-sqlite.ts",
      "src/entry-storage-libsql.ts",
      "src/entry-storage-unstorage.ts",
      "src/entry-storage-cloudflare-kv.ts",
      "src/entry-drizzle-pg.ts",
      "src/entry-drizzle-mysql.ts",
      "src/entry-drizzle-sqlite.ts",
      "src/entry-auth-none.ts",
      "src/entry-auth-basic.ts",
      "src/entry-auth-delegated.ts",
      "src/entry-authorization-none.ts",
      "src/entry-authorization-roles.ts",
      "src/entry-authorization-delegated.ts",
      "src/entry-hooks-log.ts",
    ],
    dts: true,
    format: ["esm", "cjs"],
    sourcemap: true,
    // `bun:sqlite` only exists in the Bun runtime — never bundle/resolve it.
    deps: { neverBundle: [/^bun:/] },
  },
});
