/**
 * The receiving side of the loop: a real local HTTP server that verifies every
 * delivery with `@xtandard/webhooks/receiver` — the same three lines any of
 * your consumers would write.
 *
 * To make retries visible, it deliberately answers 500 to the first
 * `failFirst` requests before starting to accept.
 */
import { verifyWebhook, type WebhookEnvelope } from "@xtandard/webhooks/receiver";

export interface ReceiverOptions {
  /** Answer 500 to this many requests before accepting (shows retries live). */
  failFirst: number;
  /**
   * The endpoint's signing secret. Read lazily per request, because the secret
   * is generated by `createEndpoint` AFTER this server must already be up.
   */
  getSecret: () => string;
}

export interface Receiver {
  url: string;
  /** Verified envelopes, in arrival order. */
  received: WebhookEnvelope[];
  close(): void;
}

export function startReceiver(options: ReceiverOptions): Receiver {
  const received: WebhookEnvelope[] = [];
  let failuresLeft = options.failFirst;

  const server = Bun.serve({
    port: 0,
    fetch: async (request) => {
      if (failuresLeft > 0) {
        failuresLeft--;
        console.log(`  [receiver] deliberately failing (${failuresLeft} failures left)`);
        return new Response("simulated outage", { status: 500 });
      }
      try {
        // THE receiver-side integration: verify the Standard Webhooks headers
        // and signature, get the parsed envelope back.
        const envelope = await verifyWebhook(request, options.getSecret());
        received.push(envelope);
        console.log(`  [receiver] verified ${envelope.type} — signature OK`);
        return new Response("ok");
      } catch {
        console.log("  [receiver] rejected: invalid signature");
        return new Response("invalid signature", { status: 401 });
      }
    },
  });

  return {
    url: `http://localhost:${server.port}/webhooks`,
    received,
    close: () => void server.stop(true),
  };
}
