/**
 * The full loop in one command: publish → sign → deliver → FAIL → retry →
 * retry → verify. The receiver (a separate local HTTP server in this process)
 * deliberately fails the first two attempts so you watch the retry schedule
 * work in real time.
 *
 *   bun run start
 *
 * Sender side: an in-memory core + dispatcher with a compressed retry schedule
 * (0s, 2s, 4s — production defaults stretch to hours).
 * Receiver side: `verifyWebhook` from `@xtandard/webhooks/receiver`.
 */
import { createDispatcher, createWebhooksCore } from "@xtandard/webhooks";
import { createMemoryStorage } from "@xtandard/webhooks/storage/memory";
import { startReceiver } from "./receiver.ts";

// --- The receiver (your consumer's side) -----------------------------------
// It needs the endpoint's secret to verify, but the secret is generated by
// createEndpoint below — so it reads the secret lazily per request.
let secret = "";
const receiver = startReceiver({ failFirst: 2, getSecret: () => secret });
console.log(`Receiver up at ${receiver.url} (will fail the first 2 attempts on purpose)\n`);

// --- The sender (your app's side) -------------------------------------------
const core = createWebhooksCore({
  storage: createMemoryStorage(),
  // Compressed so the whole story plays out in ~7 seconds. Index 0 is the
  // initial attempt's delay; each next entry is the wait after a failure.
  dispatcher: { retrySchedule: ["0s", "2s", "4s"], pollIntervalMs: 250 },
  // A metrics tap: called for every attempt, success or failure.
  onDelivery: (event) => {
    const status = event.httpStatus ?? "network-error";
    const outcome = event.ok ? "delivered" : event.terminal ? "DEAD-LETTERED" : "will retry";
    console.log(`[attempt #${event.attemptNumber}] ${event.eventType} → ${status} (${outcome})`);
  },
});

await core.createApplication({ key: "acme", name: "Acme Inc." });
await core.upsertEventType({ name: "order.completed", groupName: "Orders" });
const endpoint = await core.createEndpoint("acme", {
  url: receiver.url,
  eventTypes: ["order.completed"],
});
secret = (await core.getSecrets("acme", endpoint.id))[0]?.secret ?? "";

const dispatcher = createDispatcher(core); // picks up core.options.dispatcher
dispatcher.start();

// The one line your app actually runs. It returns immediately — delivery,
// failure, and retries all happen behind it.
const { message } = await core.publish("acme", {
  eventType: "order.completed",
  payload: { orderId: "ord_42", totalCents: 129_00, currency: "USD" },
});
console.log(`Published ${message.id} — the dispatcher takes it from here.\n`);

// --- Wait for the story to finish -------------------------------------------
const deadline = Date.now() + 30_000;
while (receiver.received.length === 0 && Date.now() < deadline) {
  await Bun.sleep(200);
}

await dispatcher.stop();
receiver.close();

if (receiver.received.length === 0) {
  console.error("\nThe delivery never landed — something is off.");
  process.exit(1);
}

const detail = await core.getDelivery("acme", (await core.listDeliveries("acme"))[0]?.id ?? "");
console.log("\nVerified envelope on the receiving side:");
console.log(JSON.stringify(receiver.received[0], null, 2));
console.log(`\nAttempt history recorded by the sender: ${detail?.attempts.length ?? 0} attempts`);
for (const attempt of detail?.attempts ?? []) {
  console.log(`  #${attempt.attemptNumber}: ${attempt.httpStatus ?? "n/a"} at ${attempt.at}`);
}
console.log("\nSame message id (webhook-id) on every attempt — receivers dedupe on it.");
process.exit(0);
